name: ci

on:
  push:
    branches:
      - "main"

env:
  REGISTRY_NAME: registry.alexjonas.com.br/command-dispatcher
  IMAGE_TAG: "V1.0.${{ github.run_number}}"
  IMAGE_COMMIT: "${{ github.sha }}"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables exposed by GitHub
        run: |
          echo "GITHUB_SHA=$GITHUB_SHA"
          export IMAGE_BUILD_VERSION="v1.0.$GITHUB_RUN_NUMBER"
          export IMAGE_NAME=""
          export IMAGE_NAME_TAGS="$IMAGE_NAME:latest,$IMAGE_NAME:$IMAGE_BUILD_VERSION"
      - name: Checkout
        uses: actions/checkout@v4

      - name: registry.alexjonas.com.br docker registry login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login registry.alexjonas.com.br -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerFile: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY_NAME }}:latest,${{ env.REGISTRY_NAME }}:${{ env.IMAGE_TAG }}

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_type: "json"
          verify_ssl: false
          webhook_auth_type: "bearer"
          data: "{ \"commit\": \"${{ env.IMAGE_COMMIT }}\" , \"image\":\"{{ env.REGISTRY_NAME }}:${{ env.IMAGE_TAG }}\" }"